return function(t, p, config)
    return {
        -- Git commit
        gitcommitSummary = { fg = t.fg, bold = true },
        gitcommitOverflow = { fg = t.error, bold = true },
        gitcommitComment = { fg = t.comment, italic = true },
        gitcommitHeader = { fg = t.keyword, bold = true },
        gitcommitOnBranch = { fg = t.keyword },
        gitcommitBranch = { fg = t.type, bold = true },
        gitcommitNoBranch = { fg = t.keyword },
        gitcommitUnmerged = { fg = t.error, bold = true },
        gitcommitUntracked = { fg = t.keyword },
        gitcommitDiscarded = { fg = t.error },
        gitcommitSelected = { fg = t.func },
        gitcommitDiscardedType = { fg = t.error },
        gitcommitSelectedType = { fg = t.func },
        gitcommitDiscardedFile = { fg = t.error },
        gitcommitSelectedFile = { fg = t.func },
        gitcommitFile = { fg = t.fg },
        gitcommitTrailerToken = { fg = t.keyword, bold = true },
        gitcommitTrailerValue = { fg = t.string },

        -- Oil.nvim
        OilFile = { fg = t.fg },
        OilDir = { fg = t.type, bold = true },
        OilSymlink = { fg = t.func, italic = true },
        OilHidden = { fg = t.keyword, italic = true },
        OilHeader = { fg = t.keyword, bold = true },
        OilBorder = { fg = t.keyword },
        OilWinBar = { fg = t.keyword },
        OilIndent = { fg = t.keyword },
        OilExpander = { fg = t.keyword },
        OilColumns = { fg = t.keyword },
        OilModified = { fg = t.error, bold = true },
        OilDeleted = { fg = t.deleted },
        OilAdded = { fg = t.added },
        OilWarning = { fg = t.warn },
        OilError = { fg = t.error },
        OilSelected = { fg = t.fg, underline = true },
        OilCursorLine = { fg = t.fg, underline = true },
        OilDirectory = { link = "OilDir" },
        OilLink = { link = "OilSymlink" },

        -- nvim-cmp
        CmpItemAbbr = { fg = t.fg },
        CmpItemAbbrDeprecated = { fg = t.keyword, strikethrough = true },
        CmpItemAbbrMatch = { fg = t.keyword, bold = true },
        CmpItemAbbrMatchFuzzy = { fg = t.keyword },
        CmpItemMenu = { fg = t.keyword, italic = true },
        CmpItemKind = { fg = t.fg },
        CmpItemKindFunction = { fg = t.func },
        CmpItemKindMethod = { fg = t.func },
        CmpItemKindConstructor = { fg = t.func },
        CmpItemKindClass = { fg = t.type },
        CmpItemKindStruct = { fg = t.type },
        CmpItemKindInterface = { fg = t.type },
        CmpItemKindTypeParameter = { fg = t.type },
        CmpItemKindModule = { fg = t.type },
        CmpItemKindNamespace = { fg = t.type },
        CmpItemKindVariable = { fg = t.variable },
        CmpItemKindProperty = { fg = t.variable },
        CmpItemKindField = { fg = t.variable },
        CmpItemKindConstant = { fg = t.constant },
        CmpItemKindEnum = { fg = t.constant },
        CmpItemKindEnumMember = { fg = t.constant },
        CmpItemKindKeyword = { fg = t.keyword },
        CmpItemKindText = { fg = t.string },
        CmpItemKindString = { fg = t.string },
        CmpItemKindColor = { fg = t.string },
        CmpItemKindSnippet = { fg = t.comment },
        CmpItemKindFile = { fg = t.fg },
        CmpItemKindFolder = { fg = t.fg },
        CmpItemKindReference = { fg = t.fg },
        CmpItemKindUnit = { fg = t.fg },
        CmpItemKindValue = { fg = t.fg },

        -- Trouble.nvim
        TroubleNormal = { fg = t.fg, bg = t.bg },
        TroubleNormalNC = { fg = t.fg_dim, bg = t.bg },
        TroubleText = { fg = t.fg, bg = t.bg },
        TroubleIndent = { fg = t.border, bg = t.bg },
        TroubleCount = { fg = t.fg, bg = t.panel_bg, bold = true },
        TroublePreview = { fg = t.fg, bg = t.panel_bg },
        TroubleDiagnosticsItemSource = { fg = t.keyword, bg = t.bg, italic = true },
        TroubleCode = { fg = t.fg_dim, bg = t.bg },
        TroubleIconDirectory = { fg = t.fg_dim, bg = t.bg },
        TroubleIconEvent = { fg = t.fg_dim, bg = t.bg },
        TroubleError = { link = "DiagnosticError" },
        TroubleWarning = { link = "DiagnosticWarn" },
        TroubleInformation = { link = "DiagnosticInfo" },
        TroubleHint = { link = "DiagnosticHint" },

        -- Telescope.nvim
        TelescopeNormal = { fg = t.fg, bg = t.bg },
        TelescopeBorder = { fg = t.border, bg = t.bg },
        TelescopeTitle = { fg = t.fg, bg = t.bg, bold = true },
        TelescopeResultsNormal = { fg = t.fg, bg = t.bg },
        TelescopeResultsBorder = { fg = t.border, bg = t.bg },
        TelescopeResultsTitle = { fg = t.fg, bg = t.bg, bold = true },
        TelescopeSelection = { fg = t.fg, bg = t.panel_bg },
        TelescopeMultiSelection = { fg = t.func, bg = t.panel_bg, bold = true },
        TelescopeSelectionCaret = { fg = t.keyword, bg = t.panel_bg },
        TelescopeMatching = { fg = t.keyword, bg = t.bg, bold = true },
        TelescopePromptNormal = { fg = t.fg, bg = t.bg },
        TelescopePromptBorder = { fg = t.border, bg = t.bg },
        TelescopePromptTitle = { fg = t.fg, bg = t.bg, bold = true },
        TelescopePromptPrefix = { fg = t.keyword, bg = t.bg },
        TelescopePromptCounter = { fg = t.keyword, bg = t.bg },
        TelescopePreviewNormal = { fg = t.fg, bg = t.bg },
        TelescopePreviewBorder = { fg = t.border, bg = t.bg },
        TelescopePreviewTitle = { fg = t.fg, bg = t.bg, bold = true },
        TelescopePreviewLine = { fg = t.fg, bg = t.panel_bg },
        TelescopePreviewMatch = { fg = t.keyword, bg = t.bg, underline = true },
        TelescopeResultsDiffAdd = { fg = t.added, bg = t.bg },
        TelescopeResultsDiffChange = { fg = t.changed, bg = t.bg },
        TelescopeResultsDiffDelete = { fg = t.deleted, bg = t.bg },

        -- fzf-lua
        FzfLuaNormal = { fg = t.fg, bg = t.bg },
        FzfLuaBorder = { fg = t.border, bg = t.bg },
        FzfLuaTitle = { fg = t.fg, bg = t.bg, bold = true },
        FzfLuaPrompt = { fg = t.keyword, bg = t.bg },
        FzfLuaInfo = { fg = t.keyword, bg = t.bg, italic = true },
        FzfLuaPath = { fg = t.type, bg = t.bg },
        FzfLuaHeaderBind = { fg = t.keyword, bg = t.bg },
        FzfLuaHeaderText = { fg = t.keyword, bg = t.bg },
        FzfLuaCursor = { fg = p.dark_navy, bg = t.fg },
        FzfLuaCursorLine = { fg = t.fg, bg = t.panel_bg },
        FzfLuaCursorLineNr = { fg = t.fg_dim, bg = t.panel_bg },
        FzfLuaMatch = { fg = t.keyword, bg = t.bg, bold = true },
        FzfLuaSearch = { fg = t.fg, bg = t.selection },
        FzfLuaMarker = { fg = t.func, bg = t.bg, bold = true },
        FzfLuaPreviewNormal = { fg = t.fg, bg = t.bg },
        FzfLuaPreviewBorder = { fg = t.border, bg = t.bg },
        FzfLuaPreviewTitle = { fg = t.fg, bg = t.bg, bold = true },
        FzfLuaPreviewLine = { fg = t.fg, bg = t.panel_bg },
        FzfLuaPreviewSearch = { fg = t.fg, bg = t.selection },
        FzfLuaPreviewMatch = { fg = t.keyword, bg = t.bg, underline = true },

        -- which-key.nvim
        WhichKey = { fg = t.func, bg = t.bg },
        WhichKeyGroup = { fg = t.type, bg = t.bg, bold = true },
        WhichKeyDesc = { fg = t.fg, bg = t.bg },
        WhichKeySeperator = { fg = t.fg_dim, bg = t.bg },
        WhichKeySeparator = { fg = t.fg_dim, bg = t.bg },
        WhichKeyFloat = { fg = t.fg, bg = t.bg },
        WhichKeyBorder = { fg = t.border, bg = t.bg },
        WhichKeyValue = { fg = t.keyword, bg = t.bg },
        WhichKeyNormal = { fg = t.fg, bg = t.bg },
        WhichKeyTitle = { fg = t.fg, bg = t.bg, bold = true },

-- nvim-notify
        NotifyBackground = { bg = p.dark_navy },

        -- Snacks.nvim
        SnacksPickerNormal = { fg = t.fg, bg = t.bg },
        SnacksPickerBorder = { fg = t.border, bg = t.bg },
        SnacksPickerTitle = { fg = t.fg, bg = t.bg, bold = true },
        SnacksPickerPrompt = { fg = t.keyword, bg = t.bg },
        SnacksPickerInput = { fg = t.fg, bg = t.bg },
        SnacksPickerInputBorder = { fg = t.border, bg = t.bg },
        SnacksPickerInputTitle = { fg = t.fg, bg = t.bg, bold = true },
        SnacksPickerList = { fg = t.fg, bg = t.bg },
        SnacksPickerListBorder = { fg = t.border, bg = t.bg },
        SnacksPickerListTitle = { fg = t.fg, bg = t.bg, bold = true },
        SnacksPickerListCursorLine = { fg = t.fg, bg = t.panel_bg },
        SnacksPickerPreview = { fg = t.fg, bg = t.bg },
        SnacksPickerPreviewBorder = { fg = t.border, bg = t.bg },
        SnacksPickerPreviewTitle = { fg = t.fg, bg = t.bg, bold = true },
        SnacksPickerPreviewLine = { fg = t.fg, bg = t.panel_bg },
        SnacksPickerMatch = { fg = t.keyword, bg = t.bg, bold = true },
        SnacksPickerDir = { fg = t.type, bg = t.bg },
        SnacksPickerFile = { fg = t.fg, bg = t.bg },
        SnacksPickerSelected = { fg = t.func, bg = t.panel_bg, bold = true },
        SnacksPickerIdx = { fg = t.fg_dim, bg = t.bg },
        SnacksPickerRow = { fg = t.fg_dim, bg = t.bg },
        SnacksPickerCol = { fg = t.fg_dim, bg = t.bg },
        SnacksPickerComment = { fg = t.comment, bg = t.bg, italic = true },
        SnacksPickerLabel = { fg = t.warn, bg = t.bg, bold = true },
    }
end
